### ISSUE TITLE
Inconsistent emph and placement for work and edu

### ISSUE THREAD

**Issue by showier-drastic** [stuxf/basic-typst-resume-template#10]
For edu, it's like this:

<img width="116" alt="img" src="https://github.com/user-attachments/assets/a7e8d551-deb9-4c38-a56a-647ef6932e7b">

But for work, it's like this:

<img width="113" alt="img" src="https://github.com/user-attachments/assets/260cdd10-82af-4811-99a6-a63b46353cb5">

I suggest swapping the order of one of them, to make it consistent.

**Comment by stuxf** [comment]
Hey, see #6, and #5, this is essentially a duplicate issue. I do see the point about them being inconsistent, but I've just been (mostly) matching the format seen [here](https://www.overleaf.com/latex/templates/jakes-resume/syzfjbzwjncs). 

That format seems to be quite popular as far as I can tell, so I do want to keep that as the default format. But I'm wondering what you think should be done about this for other people who may want to switch it around? Do you think the generic component offered is good enough or should I try implementing something different?
