### ISSUE TITLE
feature request: orcid social link

### ISSUE THREAD

**Issue by Moelf** [stuxf/basic-typst-resume-template#12]
something like this: https://tex.stackexchange.com/a/378333/72881

(I may open a PR if this feature is welcomed)

**Comment by stuxf** [comment]
Hi I think this would be a great feature to add, especially for researchers! Where on the resume do you think this would go or how do you envision this feature to be implemented?

**Comment by Moelf** [comment]
near the top next to phone numbers etc. and people can choose what to enable I guess.

**Comment by Moelf** [comment]
```typst
#import "@preview/scienceicons:0.0.6": orcid-icon

#orcid-icon(color: rgb("#AECD54")) #orcid
```

here's a nice way to render a green orcid icon
