### ISSUE TITLE
Changing font for name and information

### ISSUE THREAD

**Issue by olemartinlarsen** [stuxf/basic-typst-resume-template#3]
Hi,

I want to change the font of my name and contact information. It works fine to change the font for the other parts of the text, currently it only works to place the `#set` under the `#show`. Do you know if and how this would be possible?

```typ
#show: resume.with(
  author: name,
  //location: location,
  email: email,
  github: github,
  linkedin: linkedin,
  phone: phone,
  personal-site: personal-site,
)

#set text(font: "Equity Text A")
```

Thanks for the template btw!

**Comment by stuxf** [comment]
Hey thanks for the issue! Once it gets [merged into the main typst packages repository](https://github.com/typst/packages/pull/1092) (a day or so), you should be able to just change font in the template like this

```typst
#import "@preview/basic-resume:0.1.3": *

// ... 
#show: resume.with(
  author: name,
  //location: location,
  email: email,
  github: github,
  linkedin: linkedin,
  phone: phone,
  personal-site: personal-site,
  font: "Equity Text A",
)
```
