### ISSUE TITLE
Order and font style in sections

### ISSUE THREAD

**Issue by olemartinlarsen** [stuxf/basic-typst-resume-template#5]
Hi again,

I am tweaking my resume and there is two things I can not get quite right for it to be just right.

- The first being the order of #work section, do you know if it is possible to re-order it? What I would like in my case is to have the `company` at the top. Completely understand it if the current sorting is the one you prefer.  
- The second is in regard to font style in the different sections, is there an easy way to make one or more of the properties bold or italic in a section configuration? 

```
#work(
  title: "Subatomic Shepherd and Caffeine Connoisseur",
  location: "Atomville, CA",
  company: "Microscopic Circus, Schrodinger's University",
  dates: dates-helper(start-date: "May 2024", end-date: "Present"),
)
- more bullet points go here
```

**Comment by stuxf** [comment]
Hey! Current sorting and ordering is pretty much based off what I see most resumes tend to use, which makes it better for ATS parsing I believe. 

However, if you want, there are a couple generic components that you can use (which I should probably document haha)

```typst
generic-two-by-two(
  top-left: "",
  top-right: "",
  bottom-left: "",
  bottom-right: "",
) 
```

```typst
generic-one-by-two(
  left: "",
  right: "",
)
```

And if you want to change the boldness/italics, you can just use the functions `strong("text")` and `emph("text")`
