### ISSUE TITLE
Inconsistent date and location order

### ISSUE THREAD

**Issue by olemartinlarsen** [stuxf/basic-typst-resume-template#6]
Hi,

It seems like the order of the date and location is inconsistent for the different sections. I personally would prefer the order and text style used for the education section, do you have any thoughts on this?
<img width="760" alt="image" src="https://github.com/user-attachments/assets/449d8656-dc6c-446e-8085-053998dba4ef">

**Comment by stuxf** [comment]
See #5 , if you'd like you can reorder  it using the generic component, pretty much the same thing there :smile:

**Comment by TabError** [comment]
I find this confusing too.

What would be about an optional parameter `date-at-bottom` which defaults to True for `edu()` and is false for `work()`. This way one could easily switch between the two modes.
